"""
src/integration/adapters.py — Role interface contracts and modular adapter implementations.
Allows seamlessly plugging in new components from Role A, Role B, or Role C teammates.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Union, Any
from pathlib import Path
import json
import pandas as pd

from src.config import EXTRACTED_DIR, DOCUMENT_INDEX_PATH, QUESTIONS_PATH
from src.reference_engine.entity_store import EntityStore
from src.reference_engine.baseline_solver import BaselineSolver


class RoleAAdapter(ABC):
    """
    Interface for Role A Document Extraction output.
    """

    @abstractmethod
    def get_document(self, doc_id: str) -> Optional[dict]:
        pass

    @abstractmethod
    def get_all_documents(self) -> Dict[str, dict]:
        pass

    @abstractmethod
    def get_coverage_stats(self) -> dict:
        pass


class DefaultRoleAAdapter(RoleAAdapter):
    """
    Standard implementation reading extracted/{doc_id}.json generated by Role A.
    """

    def __init__(self, extracted_dir: Union[str, Path] = EXTRACTED_DIR, index_path: Union[str, Path] = DOCUMENT_INDEX_PATH):
        self.extracted_dir = Path(extracted_dir)
        self.index_path = Path(index_path)

    def get_document(self, doc_id: str) -> Optional[dict]:
        doc_path = self.extracted_dir / f"{doc_id}.json"
        if not doc_path.exists():
            return None
        with open(doc_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def get_all_documents(self) -> Dict[str, dict]:
        docs = {}
        for p in self.extracted_dir.glob("*.json"):
            try:
                with open(p, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    doc_id = data.get("doc_id") or p.stem
                    docs[doc_id] = data
            except Exception:
                continue
        return docs

    def get_coverage_stats(self) -> dict:
        total_indexed = 0
        if self.index_path.exists():
            df = pd.read_csv(self.index_path)
            total_indexed = len(df)
        all_docs = self.get_all_documents()
        return {
            "total_indexed": total_indexed,
            "extracted_count": len(all_docs),
            "coverage_pct": (len(all_docs) / max(total_indexed, 1)) * 100.0
        }


class RoleBAdapter(ABC):
    """
    Interface for Role B Entity Linking / Graph / Relational Store.
    """

    @abstractmethod
    def get_store(self) -> Any:
        pass


class DefaultRoleBAdapter(RoleBAdapter):
    """
    Standard implementation providing EntityStore SQLite database.
    """

    def __init__(self, store: Optional[EntityStore] = None):
        self.store = store or EntityStore()

    def get_store(self) -> EntityStore:
        return self.store


class RoleCAdapter(ABC):
    """
    Interface for Role C Question Answering / Reasoning Engine.
    """

    @abstractmethod
    def solve(self, question_obj: dict) -> Optional[float]:
        pass

    def solve_batch(self, questions_list: List[dict]) -> Dict[str, Optional[float]]:
        results = {}
        for q in questions_list:
            qid = q.get("qid")
            if qid:
                results[qid] = self.solve(q)
        return results


class BaselineRoleCAdapter(RoleCAdapter):
    """
    Reference solver implementation using BaselineSolver.
    """

    def __init__(self, solver: Optional[BaselineSolver] = None):
        self.solver = solver or BaselineSolver()

    def solve(self, question_obj: dict) -> Optional[float]:
        return self.solver.solve_question(question_obj)
